name: Devbay Chatbot Backend

on:
  workflow_dispatch:
    inputs:
      question:
        description: "User Question"
        required: true
        type: string

jobs:
  answer:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install openai

      - name: Run Chatbot
        id: chat
        run: |
          RESPONSE=$(node api/server.js "${{ github.event.inputs.question }}")
          
          # Print to logs
          echo "ANSWER: $RESPONSE"

          # Save output for frontend
          echo "$RESPONSE" > chatbot_output.txt

      - name: Commit Output File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add chatbot_output.txt
          git commit -m "Update chatbot output" || echo "No changes"
          git push
