name: Devbay Chatbot Backend

on:
  workflow_dispatch:
    inputs:
      question:
        description: "User Question"
        required: true
        type: string

jobs:
  answer:
    runs-on: ubuntu-latest

    env:
      FRONTEND_GH_TOKEN: ${{ secrets.CHATBOT_FRONTEND_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install openai

      - name: Replace Frontend Token in script.js
        run: |
          sed -i "s/__FRONTEND_GH_TOKEN__/${FRONTEND_GH_TOKEN}/g" script.js

      - name: Run Chatbot
        run: |
          node api/server.js "${{ github.event.inputs.question }}"
