name: Devbay Chatbot Backend

on:
  workflow_dispatch:
    inputs:
      question:
        description: "User Question"
        required: true
        type: string

jobs:
  answer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install openai

    - name: Run Chatbot
      run: |
        node api/server.js "${{ github.event.inputs.question }}"
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
