name: Devbay Chatbot Backend

on:
  workflow_dispatch:
    inputs:
      question:
        description: "User Question"
        required: true
        type: string

jobs:
  answer:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install openai
          npm install fs

      - name: Run Chatbot + Print Final Answer
        run: |
          echo "User asked: ${{ github.event.inputs.question }}"
          RESPONSE=$(node api/server.js "${{ github.event.inputs.question }}")

          echo "------CHATBOT_ANSWER_START------"
          echo "$RESPONSE"
          echo "------CHATBOT_ANSWER_END------"
